### ISSUE TITLE
Problem authenticating

### ISSUE THREAD

**Issue by karline** [gupta-ankit/FitgemOAuth2Rails#1]
Hi, thanks for your hard work!

I can't seem to get this to authenticate with Fitbit, either while using localhost or a remote host:

Fitbit
The app you're trying to connect did not provide valid information to Fitbit. Please report this issue to them.

Developer information: invalid_request - Invalid redirect_uri parameter value

Any thoughts? I have triple checked that the redirect_uri matches the value on Fitbit's dev site.

**Comment by albertpak** [comment]
I got kind of a similar problem:

```
The app you're trying to connect did not provide valid information to Fitbit. Please report this issue to them.

Developer information: invalid_request - Invalid redirect_uri parameter value
```

What should that `redirect_url` be and where do I set it?

**Comment by gupta-ankit** [comment]
I just made some changes to the example, based on the latest stable release of `fitgem_oauth2` (v1.0.2). Therefore, before you run the example, I recommend running the following commands from your repo root.

```
git pull origin master
bundle install
```

Now, about the authentication issue. Devise adds certain authentication routes for OAuth. You need to provide that url in your application settings.

For localhost the callback url is

http://localhost:3000/users/auth/fitbit_oauth2/callback

Here is a screenshot from my application settings

![untitled](https://cloud.githubusercontent.com/assets/931331/14274522/b9cbcfe8-fac6-11e5-977f-34fcd650a720.png)

Let me know if it works

**Comment by albertpak** [comment]
thank you for the callback URL - worked for me
